{{- if eq .Values.dockerHubSecret true }}
apiVersion: v1
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAgICAgICAgICJhdXRoIjogIk1qQXlNVEV4TVRrNk56UmtOalUwWXpJdFpEa3pNQzAwTWprNUxXSmpZek10WlRJMFpUa3pObU5tWVdVNSIKICAgICAgICB9CiAgICB9Cn0=
{{- end }}
